---
name: Test-Refcount
version: 0.06
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: assert reference counts on objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Builder::Tester: 0
  Test::More: 0
requires:
  Devel::Refcount: 0
  Scalar::Util: 0
  Test::Builder: 0
configure_requires:
  Module::Build: 0.35
provides:
  Test::Refcount:
    file: lib/Test/Refcount.pm
    version: 0.06
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
